### ISSUE TITLE
Is MAGIC a centralized framework

### ISSUE THREAD

**Issue by DongChen06** [CORE-Robotics-Lab/MAGIC#2]
hi authors, thanks for the wonderful paper and clean codes. One question is can we think of the proposed method as a centralized approach since it will output all the actions for each agent and it needs all the states to determine the graph by the Scheduler. Or does it belong to the centralized training and decentralized deploying category? Thank you so much!
![image](https://user-images.githubusercontent.com/25771207/160690727-fb037c5e-312f-464b-8180-ac287d15c824.png)

**Comment by chrisyrniu** [comment]
Hi! Thanks very much for your interest and the great question! I would like to answer your question in three folds:

1. Yes, you can regard our framework as a centralized approach because of the communication protocol, just like other communication-based methods. That is to say, agents need to send and receive messages during both training and execution. Outputting all the actions is not the reason. Actions in our framework are output in a batch-wise and decentralized manner.
2. If we do not use the communication protocol and take it out from the policy network, our method will become a fully decentralized method, i.e., decentralized training and decentralized execution. Each agent will take in its own observation and output its own action without communication. In our method, all agents share one policy network, so the observations are input to this network, and the actions are output from this network, in a batch-wise and decentralized manner, without any concatenation operation. The input and output dimensions of this policy network correspond to the ones of a single agent.
3. Furthermore, I would like to emphasize that our scheduler is light-weighted and can reduce the total centralized communication. 
    1) The scheduler itself is light-weighted because the messages are processed in a similar batch-wise manner, and no concatenation operation is needed.
    2) Supposing there are 100 agents with a communication protocol. 
        a. Without our scheduler: Each agent sends messages to all other agents, and the number of comm. will be 100 * 99 * L, where L is the number of comm. rounds.
        b. With our scheduler: Each agent only needs to send its message (i.e., the initial message) once to the scheduler, which costs 100 * 2 * 1 comm. And if the scheduler can help each agent send messages to 50 targeted agents, the number of comm. among agents will be 100 * 50 * L. Then the total amount of comm. will be 100 * (50 * L + 2), which is a considerable decrease compared to the communication protocol without the scheduler.

Please let us know if you have any questions.

Best,
Yaru

**Comment by DongChen06** [comment]
Hi, @chrisyrniu Thank you for your quick and comprehensive reply! Another question is about the designed L-round Scheduler. Each Scheduler will output an adjacency matrix, which will be fed to the Message Processor for further processing. I think it is a really good idea to make the training end-to-end with the automatically generated adjacency matrix. I want to know is there any motivation behind this idea **why we need different adjacency matrixes (graphs) in a given scenario.** For example, in a football game at a specific time step, we should pay attention to specific players? 

A further question is the Schedulers are not applied in the Junction environment. Did you try the Scheduler in the Junction env?

**Comment by chrisyrniu** [comment]
@Derekabc I would like to break down your first question into two sub-questions:
1. Why do communication patterns across agents change across timesteps in a given scenario?
    1) Intuitively, in human teams, high-performing communication usually requires reasoning about when to communicate and whom to communicate with. For example, in the 3 vs. 2 scenario in this work, the left attacker can learn to first take the ball passed from the middle attacker and then pass the ball to the right player to score. In this case, the left attacker might need to pay more attention to the middle attacker first, and then pay more attention to the right attacker.
    2) Learning “when” and “whom” have been studied and proven important to learning efficient multi-agent communication, e.g., IC3Net (A. Singh et al., ICLR 2019) and TarMAC (A. Das et al., ICML 2019).
    3) In our experiment in Google Research Football, we also tested MAGIC without the scheduler and found that the scheduler (learning “when” and “whom”) can provide a performance improvement.
2. Why do we provide the option of using different communication graphs for multiple rounds of communication at a given timestep?
    1) Intuitively, sometimes using different topologies for multi-round communication is beneficial or necessary. For example, in round 1, agent A sends a message to agent B (A→B), and then in round 2, agent B processes the message sent from agent A and gives it a feedback message (B→A). Agent A really needs agent B’s feedback (B→A) for round 2 to make its own decision, but does not need to send a new message to agent B (A→B).
    2) In our experiments, we found that using different communication graphs for multi-round communication at a given step could have better performance. Although the benefits cannot always be guaranteed, we provide this option to strengthen our method’s capability.

To answer your second question:
1. In IC3Net (A. Singh et al., ICLR 2019), communication action is always set to 1 (agents communicate all the time) to lower the burden of learning the communication action and accelerate training in a **highly vision-limited** scenario. This was stated both in the paper and in the codebase (for example, [https://github.com/IC3Net/IC3Net/issues/2](https://github.com/IC3Net/IC3Net/issues/2)). Accordingly, in our experiments, all the baselines are also set to communicate all the time in Traffic Junction.
2. We tried a few experiments and found that employing and learning a scheduler could take longer to converge to good performance in Traffic Junction with limited vision, while informative communication graphs could be learned. The Traffic Junction experiments in our paper display that just the message processor in the communication protocol, without relying on the scheduler, contributes to the success of our algorithm.

Best,
Yaru
