### ISSUE TITLE
Questions on the Scheduler

### ISSUE THREAD

**Issue by liuqianqian-x** [CORE-Robotics-Lab/MAGIC#3]
Hi authors,

 Thanks for providing the code.

From Equation (4) in your paper,  why the inputs of the Scheduler are only encoded messages {𝑚<sub>𝑖</sub><sup>𝑡(0)</sup>}<sub>1</sub><sup>𝑁</sup> which are prior to any message aggregation or processing? (This is also done in the code, e.g., [#L145](https://github.com/CORE-Robotics-Lab/MAGIC/blob/af608fda8e31d6c9acd5a63f8b55db1f0cd04f12/magic.py#L145) and [#L162](https://github.com/CORE-Robotics-Lab/MAGIC/blob/af608fda8e31d6c9acd5a63f8b55db1f0cd04f12/magic.py#L162)). Or why {𝑚<sub>𝑖</sub><sup>𝑡(𝑙)</sup>}<sub>1</sub><sup>𝑁</sup> are not passed into the Sub-Scheduler 𝑙 + 1?
![eqn4](https://user-images.githubusercontent.com/74896542/167094016-8dfa97d7-5a7e-41e1-a976-14582d467cf0.png)

Another question is it seems that there are some errors when executing the command `python plot.py saved/ title xxx`, e.g., the local variable "label" is not referenced before assignment in function parse_plot() [#L80](https://github.com/CORE-Robotics-Lab/MAGIC/blob/af608fda8e31d6c9acd5a63f8b55db1f0cd04f12/plot.py#L80) or `IsADirectoryError: Is a directory: 'saved/traffic_junction'` when there is just a file "model.pt" in the directory "\saved".

Thanks!

**Comment by chrisyrniu** [comment]
Hi, thanks for your questions! Here are my answers:

1. We tried to use the messages of round 𝑙 as inputs to the Sub-Scheduler 𝑙 + 1, but found the performance was not very good. This would accumulate the gradients from the schedulers on the message processors. Therefore, the updates of the message processors would be influenced by two types of gradients (the other type is from later rounds of message processors), and this mixture might bring harm to the learning of our GATs.
2. Running our training scripts (ending with ".sh") will generate log files ending with “.log.” Please try to put the generated log files (instead of the saved models) in the targeted folder.

Best,
Yaru

**Comment by chrisyrniu** [comment]
@liuqianqian-x I'm closing this issue. Please find our answers above. Thanks!
